# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

jobs:
  CICD:
    runs-on: ubuntu-latest
    name: A job to CICD
    steps:
      - name: Get info
        id: act1
        uses: lawbh93/VlocityCICD@latest
        with:
          branch-name: 'master'
      # Use the output from the `hello` step
      - name: Get the output branchHead
        run: echo "The output branchHead ${{ steps.act1.outputs.branchHead }}"
      - name: ReadInfo2
        env:
          TARGET: ${{ steps.act1.outputs.branchHead }}
        run: |
          bash temp.sh   
